spring:
  datasource:
    url: jdbc:mysql://database-1.c7sya24euy7i.eu-north-1.rds.amazonaws.com:3306/my_company?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  #  url: jdbc:mysql://localhost:3306/my_company?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection:
          characterEncoding: UTF-8
          useUnicode: true
        format_sql: true

  jackson:
    time-zone: UTC

  mail:
    host: smtp.gmail.com
    port: 587
    username: brkhn2248@gmail.com
    password: hpcqjlrtizfbrzyp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.security: DEBUG
    com.example.demo_project: DEBUG
