spring:
  datasource:
  #  url: jdbc:mysql://database-1.c7sya24euy7i.eu-north-1.rds.amazonaws.com:3306/my_company
    url: jdbc:mysql://localhost:3306/my_company
  #  username: admin
    username: berkhan
  #  password: 12345678
    password: 3751952b
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    time-zone: UTC

  mail:
    host: smtp.gmail.com
    port: 587
    username: brkhn2248@gmail.com
    password: hpcqjlrtizfbrzyp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.security: DEBUG  # Add this line
    com.example.demo_project: DEBUG      # Add this line
